### ISSUE TITLE
[Notificaciones] No se marcan notificaciones como vistas si el usuario tiene mas de 50

### ISSUE THREAD

**Issue by agustingazzano** [NeoCoast/homecourier-frontend#102]
**Tipo: Funcional**

**Que se esperaba que sucediera?**
Ver mis notificaciones, siendo un usuario con mas de 50 notificaciones sin ver, y que luego de ver todas las notificaciones no figure ninguna como vista.
**Qué sucedió?**
Los primeros 50 mensajes se marcan como vistos, pero el resto no.
**Pasos para reproducir el issue**
- Loggearse en el sistema como helpee o voluntario, teniendo más de 50 notificaciones sin leer.
- clickear el icono de notificaciones, y ver todas.
- clickear nuevamente el icono de notificaciones, y ver que hay notificaciones sin leer (indicadas con un punto azul como en la imagen)

![image](https://user-images.githubusercontent.com/70919699/97506071-e2557580-1958-11eb-88b9-4e93bb03f1d1.png)

**Comment by agus-ameig** [comment]
Subi esto en backend, es de backend
