### ISSUE TITLE
[Alta de helpee/volunteer] Corrección de texto

### ISSUE THREAD

**Issue by vale-git** [NeoCoast/homecourier-frontend#109]
**Tipo: No funcional**

**Que se esperaba que sucediera?**
Al registrarse correctamente como usuario, se despliega el mensaje "¡Bienvenido, {username}!"

**Que sucedió?**
Al registrarse correctamente como usuario, se despliega el mensaje "Bienvenido, {username}!" (falta el signo de exclamación ¡)

**Pasos para reproducir el issue**
- Realizar un registro como helpee o volunteer con éxito

![issue](https://user-images.githubusercontent.com/71151517/97760243-75211c00-1ae1-11eb-9156-c00172c10dbf.PNG)

**Comment by agus-ameig** [comment]
Falta el tilde en confirmación tambien, ya lo arreglo
