### ISSUE TITLE
Mensaje de error incorrecto en login

### ISSUE THREAD

**Issue by rafael-castelo** [NeoCoast/homecourier-frontend#15]
**Tipo: ** Error handling
Que se esperaba que sucediera?
Al intentar loggearse con un usuario cuyo email no fue confirmado. Se espera un mensaje de error que indica que el email no ha sido confirmado aún
Que sucedio?
El mensaje de error recibido es de credenciales inválidas
Pasos para reproducir el issue?
Dar de alta un usuario
Intentar loggearse en el sistema, sin haber confirmado el correo electrónico

**Comment by agus-ameig** [comment]
Para mí esto no debería ser así.
Como atacante si ingreso un mail y obtengo un error de que falta confirmacion del mismo, obtengo información de que ese usuario existe en el sistema.
