### ISSUE TITLE
Se prioriza mensaje de error de fecha de nacimiento sobre los demás, en Alta de Helpee

### ISSUE THREAD

**Issue by valentinseg** [NeoCoast/homecourier-frontend#24]
**Tipo:  No funcional**

**Que se esperaba que sucediera?**
Cuando una persona hace clic en el botón de Registrarse sin rellenar algún campo obligatorio, se debe desplegar un mensaje junto a cada botón indicando que es obligatorio.

**Que sucedió?**
Cuando una persona hace clic en el botón de Registrarse, sin rellenar el día y año de la fecha de nacimiento, no se despliegan los mensajes 'El campo es obligatorio' en los demás campos.

**Pasos para reproducir el issue**
- Ingresar en la página de registro para helpee (/register).
- Dar al botón de Registrarse sin rellenar ningún campo.

![imagen](https://user-images.githubusercontent.com/53498067/95031196-f4f6ca80-068a-11eb-8911-374cc436b431.png)

**Comment by agus-ameig** [comment]
Solucionado en #32
