### ISSUE TITLE
Mensaje genérico para contraseña menor a 6 caracteres, en Alta de Helpee

### ISSUE THREAD

**Issue by valentinseg** [NeoCoast/homecourier-frontend#26]
**Tipo:  No funcional**

**Que se esperaba que sucediera?**
Cuando una persona hace clic en el botón de Registrarse, cargando una contraseña con menos de 6 caracteres, despliegue un mensaje asociado al campo indicando que la misma debe tener mínimo 6 caracteres.

**Que sucedió?**
Cuando una persona hace clic en el botón de Registrarse, se despliega un mensaje genérico "Verifique que los datos introducidos sean correctos".

**Pasos para reproducir el issue**
- Ingresar en la página de registro para helpee (/register).
- Dar al botón de Registrarse con una contraseña con menos de 6 caracteres.

**Comment by agus-ameig** [comment]
Este problema se da porque falta la variable de entorno de PASSWORD_POLICY en heroku
