### ISSUE TITLE
Imagen se borra al volver a ingresar, en Alta de Helpee

### ISSUE THREAD

**Issue by valentinseg** [NeoCoast/homecourier-frontend#27]
**Tipo:  No funcional**

**Que se esperaba que sucediera?**
Cuando una persona carga una foto y vuelve a ingresar, se debería mantener la imágen si no la edita.

**Que sucedió?**
Cuando una persona vuelve a ingresar a la imagen, se borra automaticamente y se despliega el modal de carga vacío.

**Pasos para reproducir el issue**
- Ingresar en la página de registro para helpee (/register).
- Dar al botón de + para cargar una foto.
- Cargar una imagen.
- Volver a hacer clic en el botón de carga de foto.

**Comment by agus-ameig** [comment]
Solucionado en #32
