### ISSUE TITLE
[Alta de Volunteer] Foto de frente y reverso del documento permite cargar archivos en cualquier formato

### ISSUE THREAD

**Issue by valentinseg** [NeoCoast/homecourier-frontend#30]
Tipo: No funcional

Que se esperaba que sucediera?
En el formulario de registro de volunteer, cuando una persona carga una foto del frente del documento o del reverso del documento con un formato inadecuado (distinto a JPG, JPEG y PNG), se debería desplegar un mensaje de error notificando a la misma que el formato de la imagen es inadecuado.

Que sucedió?
Cuando una persona carga una foto del frente o del reverso del documento, con un formato inadecuado, se le permite continuar sin mensajes de error.

Pasos para reproducir el issue
- Ingresar en la página de registro para volunteer (/register-volunteer).
- Dar al botón de Examinar... para cargar una foto del frente o reverso del documento.
- Cargar un archivo con formato distinto a JPG, JPEG y PNG.
![imagen](https://user-images.githubusercontent.com/53498067/95534096-5684a500-09bb-11eb-9d76-9b4c65741fe9.png)

**Comment by valentinseg** [comment]
Luego de dar al botón de Registrarse, se realiza el chequeo. Entiendo igual que debería hacerse antes.

**Comment by agus-ameig** [comment]
Arreglar esto implica cambiar el comportamiento de los formularios, el chequeo evita que se envie a backend de todas maneras.
