### ISSUE TITLE
[Calificar Helpee/Volunteer] Modal de calificar no es responsive en width=360

### ISSUE THREAD

**Issue by valentinseg** [NeoCoast/homecourier-frontend#69]
**Tipo: No funcional**

**Que se esperaba que sucediera?**
Al finalizar un pedido o iniciar sesión con un usuario que no ha calificado, empleando width=360, se mostrara el modal de calificar de manera que se pueda ver las estrellas de calificación y el input de texto totalmente contenidos en el modal.

**Que sucedió?**
El modal de calificar no contiene completamente las estrellas de calificación, produciendose que en width=360 se saliesen del contenedor del modal.

**Pasos para reproducir el issue**
- Finalizar un pedido o iniciar sesión con un usuario que no ha calificado.

![imagen](https://user-images.githubusercontent.com/53498067/96953738-40510b80-14c8-11eb-9335-0f483a746bc3.png)

**Comment by manurodriguezz** [comment]
Solucionado
